class UserNotFoundError(Exception):
    pass


class UserAlreadyExistsError(Exception):
    pass
